language: node_js
node_js: '7'
cache: yarn
before_install:
- openssl aes-256-cbc -K $encrypted_1d3dc81e4ab9_key -iv $encrypted_1d3dc81e4ab9_iv
  -in id_rsa.enc -out id_rsa -d
script: npm run build
after_success: npm run docs:deploy && npm run ci:coverage
branches:
  except:
    - gh-pages
